import { stat } from "fs";
import { request } from "http";

export const QUERY_KEY = {
  draws: "draws",
  users: "users",
  drawTypes: "drawTypes",
  drawDetails: "drawDetails",
  user: "user",
  ticket: "ticket",
  notification: "notification",
  category: "category",
  wallet: "wallet",
  stakedSelections: "stakedSelections",
  results: "results",
  userTickets: "userTickets",
  transactions: "transactions",
  userDetails: "userDetails",
  winners: "winners",
  walletStat: "walletStat",
  promos: "promos",
  promoDetails: "promoDetails",
  promoRedeems: "promoRedeems",
  allPromoRedeems: "allPromoRedeems",
  allReferrals: "allReferrals",
  reports: "reports",
  content: "content",
  support: "support",
  config: "config",
  roles: "roles",
  permissions: "permissions",
  drawsByType: "drawsByType",
  paymentLogs: "paymentLogs",
  withdrawalLogs: "withdrawalLogs",
  allTickets: "allTickets",
  userStats: "userStats",
  walletModifyLogs: "walletModifyLogs",
  requestLogs: "requestLogs",
  gamePerformance: "gamePerformance",
};
